---
name: Go Tests

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  simpletest:
    name: Run a simple test on latest go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - '1.20'
        go-arch:
          - 'amd64'
        go-opsys:
          - 'linux'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests ${{ matrix.go-version }}
        run: make build

#  test:
#    name: Run Tests Against a Matrix of Environments
#    strategy:
#      fail-fast: true
#      matrix:
#        opsys:
#          - 'macos-latest'
#          - 'ubuntu-latest'
#
#        go-version:
##          - '1.18'
#          - '1.19'
#          - '1.20'
#    runs-on: ${{ matrix.opsys }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ matrix.go-version }}
#
#      - name: Run test and build binaries for ${{ matrix.go-opsys }}:${{ matrix.go-arch }}::${{ matrix.go-version }}
#        run: |
#          make build
#
#
#  build:
#    name: Run build and package
#    strategy:
#      fail-fast: true
#      matrix:
#        opsys:
#          - 'macos-latest'
#          - 'ubuntu-latest'
#        go-version:
#          - '1.20'
#    runs-on: ${{ matrix.opsys }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ matrix.go-version }}
#
#      - name: Set up Git
#        run: |
#          git config --local user.email "github.actions@samcaldwell.net"
#          git config --local user.name "Sam Caldwell (automation)"
#          git remote set-url origin https://github.com/sam-caldwell/semver.git
#
#      - name: Run test and build binaries for ${{ matrix.go-opsys }}:${{ matrix.go-arch }}::${{ matrix.go-version }}
#        run: |
#          make build package
#
#      - name: bump the version and push the new tag.
#        run: |
#          git push origin $(make version | awk '{print $2}')
#
#      - name: create release
#        run: |
#          echo "todo: create release and upload package"
