---
name: Go Tests on Main an Tagged PR for releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - v*

jobs:
  test:
    name: Run Tests Against a Matrix of Environments
    strategy:
      fail-fast: true
      matrix:
        opsys:
          - 'macos-latest'
          - 'ubuntu-latest'
        go-version:
          - '1.20'
    runs-on: ${{ matrix.opsys }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          go vet ./...

      - name: test
        run: |
          go test -v -count=1 ./...

      - name: build
        run: |
          go build -v -o build/bumpVersion cmd/bumpVersion/main.go
