---
name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    fail-fast: true
    needs: go-tests.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.email "github.actions@samcaldwell.net"
          git config --local user.name "Sam Caldwell (automation)"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Increment version
        id: incremented_version
        run: |
          make build version

      - name: Create and push tag
        if: ${{ steps.current_tag.outputs.tag != steps.incremented_version.outputs.version }}
        run: |
          git tag ${{ steps.incremented_version.outputs.version }}
#          git push origin ${{ steps.incremented_version.outputs.version }}
